name: flutter_flame_game_2
description: "Second Flutter Flame project in the monorepo."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flame: ^1.35.1
  flame_forge2d: ^0.19.2+4
  flutter_flame_game:
    path: ../flutter_flame_game
  image: ^4.7.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/stones/
