name: flutter_flame_breath_journey_game
description: "Breath Journey - Dandelion Breath Game"
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  flame: ^1.35.1
  flutter_svg: ^2.0.10+1
  permission_handler: ^12.0.1
  noise_meter: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
